apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 00-namespaces.yaml
  - 01-deployments.yaml
  - 02-cilium-policies-tenant-a.yaml
  - 03-cilium-policies-tenant-b.yaml
  - 04-cilium-policies-metadata.yaml