apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 00-namespace.yaml
  - 01-deployment-primary.yaml
  - 02-deployment-mirroring.yaml
  - 03-services.yaml
  - 04-gateway.yaml
  - 05-httproute-mirroring.yaml