# 07-role-no-access.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: no-secret-access-role
  namespace: herkules
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
